### ISSUE TITLE
How to get SOS-Match source code 

### ISSUE THREAD

**Issue by tzmzm** [mit-acl/Batvik-seasonal-dataset-loader#1]
SOS-Match is a great work for Open-Set SLAM in Unstructured Environments, Can authors keep the source code available for us?

**Comment by jkinnari** [comment]
Hi, unfortunately, the algorithm for this paper has not been made available. I recommend taking a look at [ROMAN](https://acl.mit.edu/ROMAN/), a more recent work that builds on a similar idea and includes published code.
